### ISSUE TITLE
PBJSMessageClass errors with Core gRPCs

### ISSUE THREAD

**Issue by thephez** [dashevo/js-grpc-common#10]
When processing responses for the [Core gRPCs](https://github.com/dashevo/dapi-grpc/blob/v0.12-dev/protos/core.proto), there is a failure to get past [protobufToJsonFactory](https://github.com/dashevo/js-grpc-common/blob/master/lib/client/converters/protobufToJsonFactory.js#L20) / [jsonToProtobufFactory](https://github.com/dashevo/js-grpc-common/blob/master/lib/client/converters/jsonToProtobufFactory.js#L20) (line numbers probably do not match the error messages below because I added some debugging lines).

It appears that `PBJSMessageClass` is not defined so `.decode()` and `.fromObject()` throw an error. In the case of `getStatus`, I can see the request makes it to Insight and it receives something back. It just then fails when trying to decode the response.

## protobufToJsonFactory
Returned when requesting `getStatus`:

```
{ Error: Internal error
    at rpcMethodErrorHandler (node_modules/@dashevo/grpc-common/lib/server/error/wrapInErrorHandlerFactory.js:33:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 13,
  metadataObject: undefined,
  error:
   TypeError: Cannot read property 'decode' of undefined
       at protobufToJson (node_modules/@dashevo/grpc-common/lib/client/converters/protobufToJsonFactory.js:21:8)
       at interceptedCallback (node_modules/@dashevo/grpc-common/lib/server/jsonToProtobufHandlerWrapper.js:58:30)
       at rpcMethodErrorHandler (node_modules/@dashevo/grpc-common/lib/server/error/wrapInErrorHandlerFactory.js:26:11)
       at process._tickCallback (internal/process/next_tick.js:68:7) }
```

## jsonToProtobufFactory
Returned when requesting `getBlock`:

```
{ Error: Internal error
    at rpcMethodErrorHandler (node_modules/@dashevo/grpc-common/lib/server/error/wrapInErrorHandlerFactory.js:33:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 13,
  metadataObject: undefined,
  error:
   TypeError: Cannot read property 'fromObject' of undefined
       at jsonToProtobuf (node_modules/@dashevo/grpc-common/lib/client/converters/jsonToProtobufFactory.js:21:42)
       at Object.get (node_modules/@dashevo/grpc-common/lib/server/jsonToProtobufHandlerWrapper.js:22:18)
       at getBlockHandler (lib/grpcServer/handlers/core/getBlockHandlerFactory.js:26:25)
       at rpcMethodErrorHandler (node_modules/@dashevo/grpc-common/lib/server/error/wrapInErrorHandlerFactory.js:23:30)
       at Object.methodHandler [as getBlock] (node_modules/@dashevo/grpc-common/lib/server/jsonToProtobufHandlerWrapper.js:64:12)
       at node_modules/grpc/src/server.js:593:13 }
```

Version: 0.2.0

**Comment by shumkov** [comment]
Fixed in DAPI 0.10-dev
